sonar.projectKey=mlops-local
sonar.projectName=mlops
sonar.projectVersion=1.0

sonar.sources=api,db,src,ui,workers,lakehouse
sonar.tests=tests

sonar.sourceEncoding=UTF-8
sonar.python.version=3.11

sonar.exclusions=**/__pycache__/**,**/*.pyc,**/.venv/**,**/venv/**,**/build/**,**/dist/**,**/.cursor/**,**/captures/**
