# syntax=docker/dockerfile:1.7
FROM ghcr.io/mlflow/mlflow:v2.18.0

COPY docker/requirements/mlflow.txt /tmp/requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --no-cache-dir -r /tmp/requirements.txt

EXPOSE 5000
